experimenting with how to allow other plugins to add more annotation processors. But it turns out maven doesn't fully initialize plugins until DefaultPluginManager.getConfiguredMojo() is called, and such inititalization method is not made available to the rest of the world, so when I try to load components from other modules here, they fail with NoClassDefFoundError due to missing dependencies. Furthermore, tools.jar is loaded locally in a plugin jar, so even if I manage to initialize plugins, I still won't be able to use them because they refer to different copies of tools.jar So I'm abandoning this approach, but I'm committing my experiments anyway so that it can be left in the record.